Add "decimal" and "natural" sort strategies for notation codes
NatLibFi/Skosmos pull request #1205
Opened 2021-09-14 12:28 UTC by osma

This draft PR makes it possible to select either "decimal" or "natural" sort strategy for sorting notation codes (see #937 for more background). The sorting is implemented both on the PHP and JS sides. The `skosmos:sortByNotation` configuration setting, which previously was just a boolean value, can now given a literal value to select the appropriate sort strategy:

    skosmos:sortByNotation "false";    # disabled, i.e. sort by labels, not notations
    skosmos:sortByNotation "decimal";  # decimal sorting
    skosmos:sortByNotation "natural";  # natural sorting
    skosmos:sortByNotation "true";     # default sorting i.e. decimal, as it's the most common

TODO:

- [ ] more testing - it seems that sorting by notation is not always working on the JS side because notations are missing for the jsTree concept objects
- [ ] more unit tests to check that the sort order is as expected
- [ ] update wiki documentation (Configuration)

Fixes #937

2021-09-14 12:29 UTC, osma commented on model/ConceptPropertyValue.php
> -            $label = ltrim($this->getNotation() . ' ') . $label;
Adding the notation here doesn't seem to have any effect on the sort order so I just removed it.

2021-09-14 12:30 UTC, osma commented on model/VocabularyConfig.php
> +    public function getSortByNotation(): ?string
I renamed the method for better consistency with other getters, and redefined its return value.

2021-09-14 12:31 UTC, osma commented on resource/js/scripts.js
> +// adapted to return only -1 or 1 using negVsPos function above
Looking at the documentation of the jsTree sort plugin, it expects that the return value of the sort function is either -1 or 1 (anything other than -1 will be interpreted as 1, AFAICT). To make sure that the return values meet those expectations, I added a coercing function.

2021-09-15 12:01 UTC, osma commented
> it seems that sorting by notation is not always working on the JS side because notations are missing for the jsTree concept objects

Finally found the cause of the missing notation information: the `footer.inc` customizations in the Finto layout were overriding key JS methods, and they were not in sync with changes that happened in the original Skosmos JS code (that they are based on) a long time ago. Fixed in [this Finto-data commit](https://github.com/NatLibFi/Finto-data/commit/59e5be65ca913bfda1054ab1d80fa6519ad5c584). Now the notation information is available and sorting by notation code works (both for decimal and natural sort order) in the hierarchy tree.

However, it turns out that the natural sort order is a bit different for PHP vs JS. On the PHP side, numbers with leading zeros are always first (PHP uses [Martin Pool's algorithm](http://sourcefrog.net/projects/natsort/)) The current JS implementation of naturalCompare ignores leading zeros. The differences can be seen in this screenshot, where the notation codes 33.03 and 33.04 are placed differently in the hierarchy sidebar (JS) and the concept view (PHP):

![image](https://user-images.githubusercontent.com/1132830/133429268-005a524e-bdd5-44d1-86ae-2c5e7152dbc3.png)

Not sure if this is a big issue - the example is a bit artificial, because YKL/PLC shouldn't use natural sorting but decimal, where this doesn't happen. And for vocabularies where natural sorting is preferred (i.e. PTVL), leading zeros probably shouldn't be used anyway.

2021-09-15 14:11 UTC, osma commented
I added unit tests that verify the sort order is correct on the PHP side in both "decimal" and "natural" cases. Ready for review.

I will update the wiki documentation after merging.

2021-09-15 19:50 UTC, kouralex commented
Looks great!

Three remarks, one that you already pinpointed:

Here (look at the image below) the natural order faces the same problem. I am not completely sure, if this vocabulary (HKLJ/HCLCS) should be using the "decimal" order. If that is the case (which may very well be), there is no problem as you mentioned and explained. (URL for your convenience: https://finto.fi/hklj/fi/page/001)
![image](https://user-images.githubusercontent.com/1723419/133492743-97ed8ff9-e737-49bd-83ef-908fe1b4dc89.png) 

Here, a "real" problem where irregardless of the setting, this always shows up like this: (URL for your convenience: https://finto.fi/hklj/fi/page/691.1)
![image](https://user-images.githubusercontent.com/1723419/133491351-a9689b6a-af0c-4a07-bd16-d4cc8937437c.png)

It seems like the sorting is done by the label only. For mapping properties one should probably also sort by its (if vocabulary known to Skosmos) sortByNotation setting. I am not sure if this complicates the issue a bit too much - maybe (I think) it is OK to use the same value.

Here it seems like the search is done using always the "decimal" order, even though one changes the value to "natural". This would mean that no vocabulary may use true "natural" sort strategy in search queries, am I right? The same naturally applies to the typeahead component, too (they use the same implementation under the hood).
![image](https://user-images.githubusercontent.com/1723419/133498024-69c94bf9-382f-4c22-bd1a-96b4aece1e82.png)

2021-09-15 19:54 UTC, kouralex requested changes
I already commented in the PR where I had three remarks (of which at least two require some action or explanation).

2021-09-15 20:08 UTC, kouralex commented
As a fourth item, I also noticed that with "false" value only affects concept info part - it does not affect search nor JS (this may or may not be justified):
![image](https://user-images.githubusercontent.com/1723419/133502032-830b770a-a614-46d8-954f-34bb64ef673b.png)

2021-09-16 06:53 UTC, osma commented
Thanks for the review @kouralex . You're right, I didn't consider ordering of search results at all in this PR. I will take a closer look at that and the other things you mentioned.

2021-09-16 08:23 UTC, osma commented
Renamed the "decimal" strategy to "lexical". It's not really appropriate for decimal numbers (e.g. "110" sorts before "13") but is just based on lexical string sorting. Amended the PR title and OP accordingly.

2021-09-16 10:03 UTC, osma commented
Regarding the four comments:

# 1. Different natural sort orders in PHP and JS

Already discussed above, not a big issue IMHO.

# 2. Search result order

I looked at the ordering of search results by notation in more detail and opened an issue #1209. But I don't think there's anything worth changing in this area so I set that issue to the Blue Sky milestone.

# Mapping property order

> For mapping properties one should probably also sort by its (if vocabulary known to Skosmos) sortByNotation setting. I am not sure if this complicates the issue a bit too much - maybe (I think) it is OK to use the same value.

I opened a separate issue #1208 about ordering mapping property values. I think that's out of scope for this PR and issue.

# 4. Setting "false" has no effect on hierarchy

> As a fourth item, I also noticed that with "false" value only affects concept info part - it does not affect search nor JS (this may or may not be justified):

You are right, I'm currently investigating this. I think this happens because when sorting by notation is disabled (set to false), the sorting of jsTree nodes (representing concepts) falls back to comparison of node text. But that text includes the notation code, so notation codes will affect the sorting anyway.

2021-09-16 10:31 UTC, osma commented
I fixed the JS side sorting in the hierarchy when the setting is `false`. I already responded to the three other comments above.
Ready for another round of review and (hopefully) merging @kouralex

2021-09-16 12:26 UTC, kouralex approved these changes
Seems to be working now and the issues I pinpointed have been addressed. Great job @osma !

I noticed that the default value is "false" if the property is not set at all, which kind of makes sense, however, the comments in the code imply it could be "lexical" (which is true if the value is "true"!).

Apart from that, ready for merging! 🙂

2021-09-16 13:58 UTC, osma commented
I fixed a minor JS issue and clarified the comments about default values. Will merge after tests have passed.

2021-09-16 14:03 UTC, merged