Setting the cookie for multiple vocabularies in global search
NatLibFi/Skosmos pull request #1354
Opened 2022-09-06 15:03 UTC by joelit

## Reasons for creating this PR

Cookies are not set correctly for things like multiple vocabulary selection in the global search field. This would break the global search UI element, restricting the use of global search to only skosmos API or writing the search parameters directly to the URL.

## Link to relevant issue(s), if any

- Closes #1345 

## Description of the changes in this PR

- scripts.js sets the cookie correctly, using the newly required SameSite attribute (http and https are considered to be different websites)
  - More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
- docready.js reads the selected vocabulary values correctly

## Known problems or uncertainties in this PR

Setting the language does not work either. The fix should be added here or in another PR.

## Checklist

- [x] phpUnit tests pass locally with my changes
- [x] I have added tests that show that the new code works, or tests are not relevant for this PR (e.g. only HTML/CSS changes)
- [x] The PR doesn't reduce accessibility of the front-end code (e.g. tab focus, scaling to different resolutions, use of `.sr-only` class, color contrast)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

2022-09-07 08:54 UTC, joelit commented
When fixing the language setting for the same menu, it turned out the component which writes the search query url parameters hasn't worked properly beforehand, as the paremeters aren't separeted and the parameter values are not encoded.
![Screenshot from 2022-09-07 11-29-29](https://user-images.githubusercontent.com/578627/188833741-d26b9cd7-9f4c-4b9e-a287-a6fed3177489.png)
Skosmos tries to pre-fill the search query in the text field and fails parsing it.

2022-09-13 11:36 UTC, osma requested changes
I tested this and couldn't make it not work :) Looks good, apart from the issue that "select all" doesn't set the cookie, which you already noted. I suggested a fix in the above comment. It's also possible to consider that out of scope and file a separate issue about it.

2022-09-13 12:33 UTC, joelit commented
The fix was a pretty simple one; removing the selected vocabularies and calling the updateVocabParam() function seemed to do the trick, as the empty selectedVocabs JS variable and no SKOSMOS_SELECTED value in the cookie is interpreted as having all the vocabularies chosen. :)

2022-09-13 12:42 UTC, osma approved these changes
Looks good and works perfectly! :tada: 

Before merging, I suggest changing the PR title to something more descriptive. This fixes many problems related to global search, not just setting cookies.

2022-09-13 12:49 UTC, merged