Top-level `docker-compose.yml`
NatLibFi/Skosmos pull request #1512
Opened 2023-09-08 08:21 UTC by namedgraph

## Reasons for creating this PR

`docker-compose` setup unsuitable for multiple Skosmos deployments

## Link to relevant issue(s), if any

- Closes #1511

## Description of the changes in this PR

* moved `docker-compose.yml` to the top-level dir
* fixed relative paths accordingly
* removed `container_name` properties
* replaced host port numbers with env variables with default values

## Known problems or uncertainties in this PR

Not tested directly :) But these changes work on our private fork and I was able to deploy 2 Skosmos instances on different ports on the same machine.

## Checklist

- [ ] phpUnit tests pass locally with my changes
- [ ] I have added tests that show that the new code works, or tests are not relevant for this PR (e.g. only HTML/CSS changes)
- [x] The PR doesn't reduce accessibility of the front-end code (e.g. tab focus, scaling to different resolutions, use of `.sr-only` class, color contrast)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

2023-09-19 13:31 UTC, osma requested changes
The changes here look good and the reasons behind the changes were already discussed in issue #1511.

The documentation under `dockerfiles/README.md` needs to be updated as well. Currently it says that the `docker compose` command should be run under `dockerfiles/` which obviously isn't true anymore after these changes. Also, the environment variables for setting the ports should be documented there.

When that is done (@namedgraph can you do it?) then this can be merged to `master`, i.e. Skosmos 2.x.

After that the changes should be also ported to the `skosmos-3` branch because we want to keep the Docker configuration similar for both versions. On the `skosmos-3` some additional adjustments to the phpunit and cypress test suite setup need to be done as well, probably just fixing up paths in `tests/init_containers.sh` that currently assume that the `docker-compose.yml` file is under `dockerfiles/`. I can do that once we have this in `master`.

2023-09-19 19:40 UTC, namedgraph commented
I'll try this week.

2023-10-31 08:19 UTC, osma commented
What's the status @namedgraph ? Can you fix `dockerfiles/README.md` so it syncs with the changes in this PR? Then we could merge this.

2023-10-31 09:10 UTC, namedgraph commented
@osma made changes. Are the good enough?

2023-10-31 13:09 UTC, osma commented
Looks good now so I'm merging this. Thanks a lot!

The work still needs to be ported to Skosmos 3.x but I'll take care of that later.

2023-10-31 13:09 UTC, merged