Vocab search language menu
NatLibFi/Skosmos pull request #1689
Opened 2024-10-03 10:27 UTC by joelit

## Reasons for creating this PR
The search bar language menu contents were a mockup while waiting for the translation component. This PR separates the mockup translations and adds the functionality of using the vocabulary config languages for forming the search bar language menu contents.

## Description of the changes in this PR
- Added the vocabulary config languages to the SKOSMOS object for ease of testing
- Added the functionality for using the vocab.config languages when forming the search bar language menu
- Added tests for the language menu contents
## Known problems or uncertainties in this PR

## Checklist

- [x] phpUnit tests pass locally with my changes
- [x] I have added tests that show that the new code works, or tests are not relevant for this PR (e.g. only HTML/CSS changes)
- [x] The PR doesn't reduce accessibility of the front-end code (e.g. tab focus, scaling to different resolutions, use of `.sr-only` class, color contrast)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

2024-10-03 13:11 UTC, osma requested changes
Looks good, but I suggested a couple of changes.

2024-10-03 13:11 UTC, osma commented on tests/cypress/template/vocab-search-bar.cy.js
> +          const expectedLanguages = [...win.SKOSMOS.languages, 'all'];
Relying on `win.SKOSMOS.languages` here could be problematic. What if it is not set properly based on the vocabulary configuration? Then the test could pass while the functionality is actually broken.

I suggest hardcoding the values here instead to match what is actually in the Skosmos configuration file used for the Cypress tests.

2024-10-03 13:18 UTC, joelit commented on tests/cypress/template/vocab-search-bar.cy.js
> +          const expectedLanguages = [...win.SKOSMOS.languages, 'all'];
Good point!

2024-10-09 07:55 UTC, osma approved these changes
LGTM

2024-10-09 11:09 UTC, merged