Add translations for tab-alpha.js and vocab-search.js (#1722)
NatLibFi/Skosmos pull request #1723
Opened 2024-12-17 14:52 UTC by miguelvaara

## Review guidelines

Visually observable changes in the browser are primarily related to parts generated by the following files:

- resource/js/tab-alpha.js
- resource/js/vocab-search.js

**Test the user interface:**

- Go: [our Skosmos root]/yso/fi/
- Type "pork" into the vocabulary search bar and observe the different concept types.
- Type "gdfgdgfgf" into the vocabulary search bar and observe the _No results_ text.
- Click on a letter in the alphabetical list and observe the _Loading more items_ text.

**Note:**

- The _msgs_ variable has been removed from the SKOSMOS object.
- The issue in the alphabetical list's Cypress test was caused by a timeout. For some reason in my development environment data transfer from the triple store to the frontend was so slow that an "amazingly" long wait time was required. The question remains as to how this "issue" should be properly addressed.

## Reasons for creating this PR
Improves frontend translation functionalityies.

## Link to relevant issue(s), if any
#1722 

- Closes #1722

## Description of the changes in this PR
Added similar features as in the previous Vue-related translation implementations.

## Known problems or uncertainties in this PR
What if we explore the ways to implement the translation functionality using JavaScript's promise features. By doing so, translations could be loaded in a lazy manner, meaning that if translations need to be awaited, the translation key would briefly appear to the user (likely some milliseconds), but as soon as the translations are ready, the key would be replaced with the actual translation.

This is a very common way to implement similar functionalities. The current implementation works but it has a weakness: if additional dependencies will be needed later that also need to be awaited before the page loads, they must be added to the same functionality (risk of excessive complexity).

Therefore, using the _async -> await -> response -> .then -> .catch_ structure could be considered.

## Checklist

- [x] phpUnit tests pass locally with my changes
- [x] I have added tests that show that the new code works, or tests are not relevant for this PR (e.g. only HTML/CSS changes)
- [x] The PR doesn't reduce accessibility of the front-end code (e.g. tab focus, scaling to different resolutions, use of `.sr-only` class, color contrast)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

2025-01-21 11:49 UTC, UnniKohonen requested changes
There are a few minor chnages I'd make:
- A computed value should be used for the loading message in alphabecal tab component
- The `$t` function could be called directly in the `translateType` function and `translateTypes` could be removed in vocab search component

A bigger issue is that vocab counts, alphabetical tab and vocab search Vue components all define and call the function `waitForTranslationService` which means that only one of the components can be mounted. Each of the components should get its own function for waiting for the translations (like in the term counts component).

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/vocab-search.js
> +        return this.translateTypes(type)
The `$t` function could be called directly in `translateType`.

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/vocab-search.js
> +      translateTypes (type) {
This function can be removed if `translateType` calls `$t` directly

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/tab-alpha.js
> +function waitForTranslationService () {
This function has the same name as the functions in vocab search and vocab counts. They should all be renamed.

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/tab-alpha.js
> +      loadingMoreItemsMessage () {
A computed value should be used for fetching the translation instead of a function

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/tab-alpha.js
> +      this.loadingMessage = this.loadingMoreItemsMessage() // window.SKOSMOS.msgs[window.SKOSMOS.lang]['Loading more items'] ?? window.SKOSMOS.msgs.en['Loading more items']
This can be removed if a computed value is used for the message

2025-01-21 11:49 UTC, UnniKohonen commented on resource/js/tab-alpha.js
> +        loadingMessage: '',
`loadingMessage` can be removed from data if a computed value is used

2025-01-21 13:45 UTC, miguelvaara commented on resource/js/vocab-search.js
> +      translateTypes (type) {
Removed

2025-01-21 14:17 UTC, miguelvaara commented on resource/js/tab-alpha.js
> +function waitForTranslationService () {
Moved out of the global scope to local scope, renamed and in addition, refactored into arrow functions.

2025-01-21 14:38 UTC, miguelvaara commented on resource/js/tab-alpha.js
> +      loadingMoreItemsMessage () {
Good point! Thanks :-). Fixed!

2025-01-21 14:42 UTC, miguelvaara commented on resource/js/tab-alpha.js
> +        loadingMessage: '',
Fixed

2025-01-21 15:07 UTC, miguelvaara commented on resource/js/tab-alpha.js
> +      this.loadingMessage = this.loadingMoreItemsMessage() // window.SKOSMOS.msgs[window.SKOSMOS.lang]['Loading more items'] ?? window.SKOSMOS.msgs.en['Loading more items']
There was something here that I did not fully grasp, but that' s okay. I understand that variables defined in `computed` can be used "directly," but I still think the use of a lifecycle hook would have been necessary. However, it seems to work without it. I did as you suggested, as it works. :-)

2025-01-22 07:24 UTC, osma commented
This PR seems to contain commits merged from the main branch (e.g. the PHPUnit 10 upgrade), which make the commit history and GitHub diff view a bit messy. Maybe it would help to switch the base branch briefly to something else and back to `main`, that would at least force GitHub to recompute the diff view, hopefully making it cleaner.

2025-01-22 14:33 UTC, osma commented
Now the merge conflicts have been resolved and the unnecessary 20 second waits in Cypress tests have been removed. :tada:

2025-01-23 06:32 UTC, UnniKohonen approved these changes
LGTM!

2025-01-23 08:21 UTC, merged